In [2]:
#Problem Statement1: Write a Python program to multiply a M×N matrix by N×A matrix and create a real matrix product.

import numpy as np
a = np.random.random((5,3))
print("First array:")
print(a)
b = np.random.random((3,2))
print("Second array:")
print(b)
c = np.dot(a,b)
print("Dot product of two arrays:")
print(c)

First array:
[[0.08576882 0.13184597 0.87886807]
 [0.35478877 0.67326452 0.13611673]
 [0.89975346 0.933729   0.07655145]
 [0.44494689 0.44896248 0.35978928]
 [0.47336225 0.79667938 0.55207666]]
Second array:
[[0.75736243 0.10171589]
 [0.76442405 0.40449435]
 [0.12964977 0.00277008]]
Dot product of two arrays:
[[0.27968936 0.06448954]
 [0.80101078 0.30879641]
 [1.40512925 0.46941939]
 [0.72683038 0.2278576 ]
 [1.03908427 0.37193007]]


In [3]:
#Problem Statement2: 
#Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.

x = np.array(['Python','PHP','JS','Example','html5','5'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r1 = np.char.isdigit(x)
r2 = np.char.islower(x)
r3 = np.char.isupper(x)
print("Digits only =",r1)
print("Lower case only =",r2)
print("Upper case only = ",r3)


Original Array:
['Python' 'PHP' 'JS' 'Example' 'html5' '5']
Digits only = [False False False False False  True]
Lower case only = [False False False False  True False]
Upper case only =  [False  True  True False False False]


C:\Users\Admin\AppData\Local\Temp\ipykernel_16672\2349937209.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['Python','PHP','JS','Example','html5','5'], dtype=np.str)


Problem Statement3:Write a program thatreads two space-separated positive integers X and Y
    as input and perform the following tasks:Tasks to be performed:
            1.Create a list (lst1) starting at one (1) with 16 elements at a step of X
            2.Create a list (lst2) starting at one (1) with 16 elements at a step of 푌
            3.Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
            4.Reshape both the NumPy arrays to (4,4)5.
            Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)
            6.Print all the elements of np3 in a single dimension list like the format as shown below:
                a.[n0 n1 n2 n3 n4 n5 n6 n7 n8]

    

In [29]:
# 

given_string = '7 9'
X,Y = map(int, given_string.split())

lst1 = list(range(1, 1+16*X, X))
print(lst1)

lst2 = list(range(1, 1+16*Y, Y))
print(lst2)

np1 = np.array(lst1)
np2 = np.array(lst2)

np1 = np1.reshape(4,4)
np2 = np2.reshape(4,4)

np3 = np1 - np2

print(np3.flatten().tolist())

[1, 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99, 106]
[1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91, 100, 109, 118, 127, 136]
[0, -2, -4, -6, -8, -10, -12, -14, -16, -18, -20, -22, -24, -26, -28, -30]


Problem Statement4: 
    Write a Python program thattakes two integer-NumPy arrays, 
    P and Q of shape [3∗3]and performthe following task:
        
Task to be performed:Print the element-wise difference of the matrix P and Q (P−Q).

In [30]:

P = [[23, 56, 87], [3, 6, 96], [4, 6, 78]]
Q = [[12, 34, 54], [7, 2, 54], [6, 2, 78]]
result = [[P[i][j] - Q[i][j]  for j in range(len(P[0]))] for i in range(len(Q))]

for r in result:
    print(r)

[11, 22, 33]
[-4, 4, 42]
[-2, 4, 0]
